# -*- coding: utf-8 -*-
"""hfi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZNbpO3qbX01bX70EbkdVg-sdomy9BKL
"""

from google.colab import drive
import pandas as pd

# Mount Drive
drive.mount('/content/drive')

# Imports
# -----------------------------
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output

# Load your preprocessed dataset
file_path = '/content/drive/MyDrive/data_usd_preprocessed.csv'
df = pd.read_csv(file_path)

# Spending categories & recommended percentages
# -----------------------------
features = ['Rent','Groceries','Transport','Eating_Out','Entertainment','Utilities']
ideal_percent = {
    'Rent': 0.3,
    'Groceries': 0.15,
    'Transport': 0.1,
    'Eating_Out': 0.1,
    'Entertainment': 0.05,
    'Utilities': 0.1
}

# Weights for FHI components
weights = {
    'savings_rate': 30,
    'debt_to_income': 25,
    'category_spending': 25,
    'subscription': 20
}

# Create input widgets
# -----------------------------
inputs = {}
for feature in features:
    inputs[feature] = widgets.FloatText(
        value=0,
        description=feature,
        step=1
    )

income_input = widgets.FloatText(value=1000, description="Income")
debt_input = widgets.FloatText(value=0, description="Debt")
subscription_input = widgets.FloatText(value=0, description="Subscriptions")

calculate_button = widgets.Button(description="Calculate FHI")
reset_button = widgets.Button(description="Reset")
output = widgets.Output()

# FHI calculation logic
# -----------------------------
def calculate_fhi(income, debt, subscription, spending):
    total_spent = sum(spending.values())
    savings = max(income - total_spent, 0)

    # 1️⃣ Savings rate
    savings_rate = savings / income
    savings_score = savings_rate * weights['savings_rate']

    # 2️⃣ Debt-to-income ratio
    debt_ratio_score = (1 - min(debt / income, 1)) * weights['debt_to_income']

    # 3️⃣ Category spending vs ideal
    category_score = 0
    for cat in features:
        actual_pct = spending[cat] / income
        ideal_pct = ideal_percent[cat]
        # max score if actual <= ideal
        score = min(ideal_pct / actual_pct, 1) if actual_pct > 0 else 1
        category_score += score
    category_score = (category_score / len(features)) * weights['category_spending']

    # 4️⃣ Subscription / non-essential
    recommended_max_sub = 0.1 * income  # 10% of income recommended
    sub_score = max((recommended_max_sub - subscription) / recommended_max_sub, 0)
    sub_score = sub_score * weights['subscription']

    # Total FHI
    fhi = savings_score + debt_ratio_score + category_score + sub_score
    fhi = min(round(fhi,2), 100)

    # Rating
    if fhi < 40:
        rating = "Poor"
    elif fhi < 61:
        rating = "Average"
    elif fhi < 81:
        rating = "Good"
    else:
        rating = "Excellent"

    return fhi, rating

# Button actions
# -----------------------------
def on_calculate_clicked(b):
    clear_output()
    display(widgets.VBox(list(inputs.values()) + [income_input, debt_input, subscription_input, calculate_button, reset_button]))

    spending = {feature: inputs[feature].value for feature in features}
    income_val = income_input.value
    debt_val = debt_input.value
    sub_val = subscription_input.value

    fhi_score, rating = calculate_fhi(income_val, debt_val, sub_val, spending)

    print(f"💳 Financial Health Index (FHI): {fhi_score} / 100")
    print(f"🏷 Rating: {rating}")

def on_reset_clicked(b):
    for feature in features:
        inputs[feature].value = 0
    income_input.value = 1000
    debt_input.value = 0
    subscription_input.value = 0

calculate_button.on_click(on_calculate_clicked)
reset_button.on_click(on_reset_clicked)

# Display widgets
# -----------------------------
display(widgets.VBox(list(inputs.values()) + [income_input, debt_input, subscription_input, calculate_button, reset_button]))

