# -*- coding: utf-8 -*-
"""ScenarioSimulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_XOue0KIB0wf3-1I2mGG_lv0xlLrTo2
"""

from google.colab import drive
import pandas as pd

# Mount Drive
drive.mount('/content/drive')

# Imports
# -----------------------------
import pandas as pd
import numpy as np
import ipywidgets as widgets
from IPython.display import display, clear_output

# Load your preprocessed dataset
file_path = '/content/drive/MyDrive/data_usd_preprocessed.csv'
df = pd.read_csv(file_path)

features = ['Rent','Groceries','Transport','Eating_Out','Entertainment','Utilities']
average_spend = df[features].mean()
average_income = df['Income'].mean()

# Create widgets
# -----------------------------
inputs_percent = {}
for feature in features:
    inputs_percent[feature] = widgets.FloatSlider(
        value=0,
        min=-100, max=100, step=1,
        description=f"{feature} %",
        continuous_update=False
    )

user_income = widgets.FloatText(
    value=average_income,
    description="Income",
    step=0.01
)

simulate_button = widgets.Button(description="Simulate Scenario")
reset_button = widgets.Button(description="Reset")

# Scenario simulation logic
# -----------------------------
def simulate_scenario(user_income_val, adjustments):
    new_spending = {}
    potential_savings = 0

    for feature in features:
        current = average_spend[feature]  # baseline average spending
        change_pct = adjustments[feature] / 100
        new_amount = current * (1 + change_pct)
        new_spending[feature] = round(new_amount, 2)

        # realistic savings: can't save more than what you spend
        saving = max(average_spend[feature] - new_amount, 0)
        potential_savings += saving

    # cap savings to income
    potential_savings = min(potential_savings, user_income_val)
    return new_spending, round(potential_savings,2)

# Button actions
# -----------------------------
def on_simulate_clicked(b):
    clear_output()
    display(widgets.VBox(list(inputs_percent.values()) + [user_income, simulate_button, reset_button]))

    adjustments = {feature: inputs_percent[feature].value for feature in features}
    income_val = user_income.value
    new_spending, savings = simulate_scenario(income_val, adjustments)

    print("📊 Scenario Simulation Results:")
    for k,v in new_spending.items():
        print(f"- {k}: ${v}")
    print(f"\n💰 Potential savings compared to baseline: ${savings}")

def on_reset_clicked(b):
    for feature in features:
        inputs_percent[feature].value = 0
    user_income.value = average_income

simulate_button.on_click(on_simulate_clicked)
reset_button.on_click(on_reset_clicked)

# Display widgets
# -----------------------------
display(widgets.VBox(list(inputs_percent.values()) + [user_income, simulate_button, reset_button]))